services:
  - type: web
    name: subsphere
    runtime: image
    repo: https://github.com/Krishna-110/Subsphere
    branch: main
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
