services:
  - type: web
    name: subsphere
    env: docker
    repo: https://github.com/Krishna-110/Subsphere
    branch: main
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    autoDeploy: yes
    envVars:
      - key: DATABASE_URL
        value: $SUBSPHERE_DATABASE_URL
      - key: DATABASE_USERNAME
        value: $SUBSPHERE_DATABASE_USERNAME
      - key: DATABASE_PASSWORD
        value: $SUBSPHERE_DATABASE_PASSWORD
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  - type: postgresql
    name: subsphere-db
    plan: free
    region: singapore
