spring.application.name=subsphere
server.port=8080

# Database Connection Settings
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/saas_platform_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email

# Stripe Payment Configuration
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Redis Cache Configuration
spring.data.redis.url=${REDIS_URL:rediss://default:gQAAAAAAAQMcAAIncDJmYWQ5ZDMxYWM0YjY0NzNlOGIwMDJmZGI2ZTFjOGRlOHAyNjYzMzI@keen-parrot-66332.upstash.io:6379}

# Google Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}

logging.level.org.springframework.security=TRACE